// Ciudades agrupadas por país → se exportan como "Ciudad, País"
const BY_COUNTRY: Record<string, string[]> = {
  "España": [
    // Madrid (barrios y municipios)
    "Salamanca, Madrid", "Chamberí, Madrid", "Malasaña, Madrid", "Chueca, Madrid",
    "Lavapiés, Madrid", "La Latina, Madrid", "Moncloa, Madrid", "Tetuán, Madrid",
    "Hortaleza, Madrid", "Vallecas, Madrid", "Carabanchel, Madrid", "Arganzuela, Madrid",
    "Retiro, Madrid", "Moratalaz, Madrid", "Usera, Madrid", "Villaverde, Madrid",
    "Fuencarral, Madrid", "Ciudad Lineal, Madrid", "Barajas, Madrid",
    "Móstoles", "Alcobendas", "Getafe", "Leganés", "Alcalá de Henares",
    "Torrejón de Ardoz", "Fuenlabrada", "Parla", "Alcorcón", "Pozuelo de Alarcón",
    "Las Rozas", "Majadahonda", "Boadilla del Monte", "Rivas-Vaciamadrid",
    "Collado Villalba", "San Sebastián de los Reyes", "Coslada", "Valdemoro",
    // Barcelona
    "Gràcia, Barcelona", "Eixample, Barcelona", "Poblenou, Barcelona", "Sants, Barcelona",
    "Sant Andreu, Barcelona", "Les Corts, Barcelona", "Sarrià, Barcelona", "Horta, Barcelona",
    "El Born, Barcelona", "Barceloneta, Barcelona", "Raval, Barcelona", "Poble Sec, Barcelona",
    "Clot, Barcelona",
    "Badalona", "L'Hospitalet de Llobregat", "Sabadell", "Terrassa", "Mataró",
    "Cornellà de Llobregat", "Sant Cugat del Vallès", "Rubí", "Granollers",
    "El Prat de Llobregat", "Gavà", "Castelldefels", "Vilanova i la Geltrú", "Manresa",
    "Igualada", "Tarragona", "Reus", "Lleida", "Girona",
    // Valencia
    "Ruzafa, Valencia", "El Cabanyal, Valencia", "Benimaclet, Valencia", "Campanar, Valencia",
    "Patraix, Valencia", "Jesús, Valencia", "Algirós, Valencia",
    "Alboraya", "Torrent", "Gandia", "Sagunto", "Alzira", "Ontinyent",
    "Elche", "Alicante", "Benidorm", "Torrevieja", "Orihuela", "Santa Pola",
    "Castellón de la Plana", "Vila-real", "Burriana", "Vinaròs",
    // Andalucía
    "Triana, Sevilla", "Los Remedios, Sevilla", "Nervión, Sevilla", "Macarena, Sevilla",
    "Dos Hermanas", "Alcalá de Guadaíra", "Écija", "Carmona",
    "Marbella", "Fuengirola", "Torremolinos", "Estepona", "Mijas", "Vélez-Málaga",
    "Antequera", "Ronda", "Nerja",
    "Jerez de la Frontera", "El Puerto de Santa María", "San Fernando", "Algeciras",
    "La Línea de la Concepción", "Chiclana de la Frontera", "Sanlúcar de Barrameda",
    "Córdoba", "Lucena",
    "Granada", "Motril", "Baza",
    "Almería", "El Ejido", "Roquetas de Mar",
    "Jaén", "Linares", "Úbeda", "Baeza",
    "Huelva", "Lepe", "Moguer",
    // País Vasco y Navarra
    "Bilbao", "Getxo", "Barakaldo", "Portugalete", "Sestao",
    "San Sebastián", "Irún", "Errenteria",
    "Vitoria-Gasteiz",
    "Pamplona", "Tudela",
    "Logroño", "Calahorra",
    // Norte y Galicia
    "Oviedo", "Gijón", "Avilés",
    "Santander", "Torrelavega",
    "Vigo", "Pontevedra", "A Coruña", "Santiago de Compostela", "Ferrol", "Lugo", "Ourense",
    // Castilla y otras
    "Zaragoza", "Huesca", "Teruel",
    "Valladolid", "Burgos", "Salamanca", "Ávila", "Segovia", "Palencia", "León", "Zamora",
    "Toledo", "Talavera de la Reina", "Ciudad Real", "Albacete", "Cuenca", "Guadalajara",
    "Badajoz", "Mérida", "Cáceres",
    "Murcia", "Cartagena", "Lorca",
    // Islas
    "Las Palmas de Gran Canaria", "Santa Cruz de Tenerife", "La Laguna", "Arona", "Adeje",
    "Puerto de la Cruz", "Arrecife", "Puerto del Rosario",
    "Palma de Mallorca", "Calvià", "Manacor", "Inca", "Ibiza", "Mahón",
  ],

  "México": [
    // CDMX colonias
    "Polanco, CDMX", "Roma Norte, CDMX", "Roma Sur, CDMX", "Condesa, CDMX",
    "Coyoacán, CDMX", "Del Valle, CDMX", "Narvarte, CDMX", "Nápoles, CDMX",
    "Doctores, CDMX", "Centro Histórico, CDMX", "Tlatelolco, CDMX",
    "Santa Fe, CDMX", "Lomas de Chapultepec, CDMX",
    "Xochimilco, CDMX", "Iztapalapa, CDMX", "Azcapotzalco, CDMX",
    "Gustavo A. Madero, CDMX", "Álvaro Obregón, CDMX", "Tlalpan, CDMX",
    "Benito Juárez, CDMX", "Miguel Hidalgo, CDMX",
    // Estado de México
    "Satélite, Estado de México", "Tlalnepantla", "Naucalpan", "Nezahualcóyotl",
    "Ecatepec", "Texcoco", "Atizapán de Zaragoza", "Cuautitlán Izcalli",
    // Guadalajara
    "Zapopan", "Tlaquepaque", "Providencia, Guadalajara", "Chapalita, Guadalajara",
    "Americana, Guadalajara", "Lafayette, Guadalajara", "Tonalá", "Tlajomulco de Zúñiga",
    // Monterrey
    "San Pedro Garza García", "Cumbres, Monterrey", "Valle Oriente, Monterrey",
    "Mitras, Monterrey", "Obispado, Monterrey", "Apodaca", "Guadalupe, Nuevo León",
    "Santa Catarina, Nuevo León", "Escobedo",
    // Puebla y Querétaro
    "Angelópolis, Puebla", "Cholula", "San Andrés Cholula", "Atlixco", "Tehuacán",
    "Querétaro", "San Juan del Río", "Corregidora",
    // Guanajuato y Bajío
    "León", "Irapuato", "Celaya", "Guanajuato", "Silao",
    "San Luis Potosí", "Aguascalientes",
    // Occidente
    "Morelia", "Uruapan", "Zamora de Hidalgo",
    "Colima", "Manzanillo",
    "Puerto Vallarta",
    // Norte
    "Culiacán", "Mazatlán", "Los Mochis",
    "Hermosillo", "Obregón", "Nogales",
    "Chihuahua", "Ciudad Juárez", "Delicias",
    "Tijuana", "Mexicali", "Ensenada", "La Paz",
    "Torreón", "Saltillo", "Monclova",
    "Durango", "Zacatecas",
    // Sur y Sureste
    "Mérida", "Cancún", "Playa del Carmen", "Cozumel",
    "Villahermosa", "Tuxtla Gutiérrez", "San Cristóbal de las Casas",
    "Oaxaca", "Puerto Escondido", "Huatulco",
    "Acapulco", "Chilpancingo",
    "Veracruz", "Xalapa", "Coatzacoalcos", "Poza Rica",
    "Cuernavaca", "Jiutepec",
    "Tapachula",
  ],

  "Colombia": [
    // Medellín
    "El Poblado, Medellín", "Laureles, Medellín", "Belén, Medellín",
    "Castilla, Medellín", "Aranjuez, Medellín", "La América, Medellín",
    "Envigado", "Bello", "Itagüí", "Sabaneta", "La Estrella",
    // Bogotá
    "Chapinero, Bogotá", "Usaquén, Bogotá", "Suba, Bogotá", "Kennedy, Bogotá",
    "Bosa, Bogotá", "Engativá, Bogotá", "Fontibón, Bogotá", "Teusaquillo, Bogotá",
    "Barrios Unidos, Bogotá", "Antonio Nariño, Bogotá", "Santa Fe, Bogotá",
    // Cali
    "Cali", "Palmira", "Buenaventura", "Jamundí", "Yumbo",
    // Otras ciudades
    "Barranquilla", "Soledad", "Malambo",
    "Cartagena de Indias", "Turbaco",
    "Bucaramanga", "Floridablanca", "Girón", "Piedecuesta",
    "Pereira", "Dosquebradas", "Santa Rosa de Cabal",
    "Manizales", "Villamaría",
    "Armenia", "Montenegro",
    "Cúcuta", "Villa del Rosario",
    "Ibagué", "Neiva", "Pitalito",
    "Popayán", "Santa Marta", "Valledupar",
    "Montería", "Sincelejo", "Villavicencio", "Pasto",
  ],

  "Argentina": [
    // Buenos Aires barrios
    "Palermo, Buenos Aires", "Belgrano, Buenos Aires", "Caballito, Buenos Aires",
    "Flores, Buenos Aires", "Villa Crespo, Buenos Aires", "San Telmo, Buenos Aires",
    "Puerto Madero, Buenos Aires", "Recoleta, Buenos Aires", "Barracas, Buenos Aires",
    "La Boca, Buenos Aires", "Almagro, Buenos Aires", "Boedo, Buenos Aires",
    "Villa del Parque, Buenos Aires", "Devoto, Buenos Aires", "Saavedra, Buenos Aires",
    "Núñez, Buenos Aires", "Villa Urquiza, Buenos Aires", "Balvanera, Buenos Aires",
    // GBA
    "San Isidro", "Vicente López", "Tigre", "San Martín, GBA",
    "Morón", "Hurlingham", "La Matanza", "Lanús", "Lomas de Zamora",
    "Quilmes", "Berazategui", "Florencio Varela", "Ezeiza",
    "Merlo", "Moreno", "Luján",
    // Interior
    "Córdoba", "Villa Carlos Paz", "Alta Gracia", "Río Cuarto", "Villa María",
    "Rosario", "Venado Tuerto", "Rafaela", "Santa Fe",
    "Mendoza", "Godoy Cruz", "Guaymallén", "San Rafael",
    "La Plata", "Mar del Plata", "Bahía Blanca", "Tandil",
    "Tucumán", "Tafí Viejo",
    "Salta", "Jujuy", "Posadas", "Corrientes",
    "Resistencia", "Paraná", "Concordia",
    "San Juan", "San Luis", "Neuquén", "Cipolletti",
    "Bariloche", "Comodoro Rivadavia", "Ushuaia",
  ],

  "Perú": [
    // Lima distritos
    "Miraflores, Lima", "San Isidro, Lima", "Surco, Lima", "La Molina, Lima",
    "Barranco, Lima", "San Borja, Lima", "Magdalena del Mar, Lima",
    "Jesús María, Lima", "Lince, Lima", "Pueblo Libre, Lima",
    "San Miguel, Lima", "Chorrillos, Lima", "Surquillo, Lima",
    "San Juan de Lurigancho, Lima", "Los Olivos, Lima", "Independencia, Lima",
    "Ate, Lima", "Santa Anita, Lima",
    "Callao", "La Perla, Callao",
    // Otras ciudades
    "Arequipa", "Cayma", "Yanahuara", "Cerro Colorado",
    "Trujillo", "Víctor Larco Herrera", "Chiclayo", "José Leonardo Ortiz",
    "Piura", "Sullana", "Iquitos", "Cusco",
    "Puno", "Juliaca", "Tacna", "Huancayo", "Ica", "Chimbote",
  ],

  "Venezuela": [
    "Chacao, Caracas", "Baruta, Caracas", "El Hatillo, Caracas",
    "Las Mercedes, Caracas", "La Florida, Caracas", "Altamira, Caracas",
    "Los Palos Grandes, Caracas", "El Paraíso, Caracas",
    "Maracaibo", "San Francisco, Maracaibo",
    "Valencia", "Naguanagua", "San Diego",
    "Barquisimeto", "Cabudare",
    "Maracay", "Turmero",
    "San Cristóbal", "Barcelona, Anzoátegui", "Puerto La Cruz",
    "Maturín", "Cumaná", "Puerto Ordaz", "Mérida",
  ],

  "Chile": [
    // Santiago comunas
    "Providencia, Santiago", "Las Condes, Santiago", "Ñuñoa, Santiago", "Vitacura, Santiago",
    "La Florida, Santiago", "Maipú", "Pudahuel", "Quilicura",
    "Peñalolén", "Puente Alto", "La Reina, Santiago", "Macul",
    "Lo Barnechea", "Huechuraba", "Recoleta, Santiago", "Independencia, Santiago",
    "Estación Central", "Santiago Centro",
    // Otras ciudades
    "Valparaíso", "Viña del Mar", "Quilpué", "Villa Alemana",
    "Concepción", "Talcahuano", "Coronel",
    "La Serena", "Coquimbo", "Antofagasta", "Arica", "Iquique",
    "Temuco", "Padre Las Casas", "Valdivia", "Puerto Montt", "Osorno",
    "Chillán", "Rancagua", "Talca", "Curicó",
  ],

  "Ecuador": [
    "La Mariscal, Quito", "González Suárez, Quito", "El Batán, Quito",
    "Iñaquito, Quito", "Cotocollao, Quito", "Cumbayá", "Tumbaco",
    "Urdesa, Guayaquil", "Kennedy, Guayaquil", "Alborada, Guayaquil",
    "Ceibos, Guayaquil", "Samborondón", "Daule", "Durán",
    "Cuenca", "Manta", "Portoviejo", "Loja", "Ambato",
    "Riobamba", "Machala", "Santo Domingo de los Tsáchilas", "Ibarra",
  ],

  "Guatemala": [
    "Zona 10, Guatemala City", "Zona 14, Guatemala City",
    "Zona 15, Guatemala City", "Zona 16, Guatemala City",
    "Mixco", "Villa Nueva", "Antigua Guatemala",
    "Quetzaltenango", "Escuintla", "Cobán",
    "Chiquimula", "Puerto Barrios", "Mazatenango",
  ],

  "Cuba": [
    "Vedado, La Habana", "Miramar, La Habana", "Playa, La Habana",
    "Centro Habana", "La Habana Vieja", "Cerro, La Habana",
    "Santiago de Cuba", "Holguín", "Camagüey", "Santa Clara",
    "Guantánamo", "Bayamo", "Matanzas", "Cienfuegos", "Pinar del Río",
  ],

  "República Dominicana": [
    "Piantini, Santo Domingo", "Naco, Santo Domingo", "Evaristo Morales, Santo Domingo",
    "Bella Vista, Santo Domingo", "Los Cacicazgos, Santo Domingo",
    "Los Prados, Santo Domingo", "Arroyo Hondo, Santo Domingo",
    "Santiago de los Caballeros", "La Vega", "San Pedro de Macorís",
    "La Romana", "Puerto Plata", "Higüey",
  ],

  "Bolivia": [
    "Sopocachi, La Paz", "Miraflores, La Paz", "San Miguel, La Paz",
    "Calacoto, La Paz", "Zona Sur, La Paz", "El Alto",
    "Cochabamba", "Sacaba", "Quillacollo",
    "Santa Cruz de la Sierra", "Warnes", "Montero",
    "Oruro", "Potosí", "Sucre", "Tarija",
  ],

  "Honduras": [
    "Tegucigalpa", "Comayagüela",
    "San Pedro Sula", "Choloma", "La Lima", "Puerto Cortés",
    "El Progreso", "La Ceiba", "Choluteca",
  ],

  "Paraguay": [
    "Asunción", "Fernando de la Mora", "Lambaré", "Luque",
    "San Lorenzo", "Capiatá", "Limpio",
    "Encarnación", "Ciudad del Este", "Concepción",
  ],

  "El Salvador": [
    "San Salvador", "Santa Tecla", "Antiguo Cuscatlán",
    "Mejicanos", "Soyapango", "Apopa",
    "Santa Ana", "San Miguel",
  ],

  "Nicaragua": [
    "Managua", "Ciudad Sandino", "Masaya",
    "León", "Chinandega", "Matagalpa", "Estelí", "Granada",
  ],

  "Costa Rica": [
    "Escazú", "Santa Ana, San José", "Desamparados",
    "Alajuela", "Heredia", "Cartago", "Liberia",
    "Pérez Zeledón", "San Carlos",
  ],

  "Panamá": [
    "Ciudad de Panamá", "San Miguelito", "Arraiján", "La Chorrera",
    "Colón", "David", "Santiago de Veraguas", "Chitré",
  ],

  "Uruguay": [
    "Pocitos, Montevideo", "Punta Carretas, Montevideo", "Malvín, Montevideo",
    "Carrasco, Montevideo", "Cordón, Montevideo", "Punta Gorda, Montevideo",
    "Salto", "Paysandú", "Maldonado", "Punta del Este", "Las Piedras", "Canelones",
  ],

  "Puerto Rico": [
    "Santurce, San Juan", "Miramar, San Juan", "Condado, San Juan",
    "Isla Verde, San Juan", "Bayamón", "Carolina", "Ponce",
    "Caguas", "Mayagüez", "Arecibo", "Guaynabo", "Trujillo Alto",
  ],
};

// Exporta strings planos con "Ciudad, País" para el random picker
const CITIES: string[] = Object.entries(BY_COUNTRY).flatMap(
  ([country, cities]) => cities.map((city) => `${city}, ${country}`)
);

export const CITIES_EN: string[] = [
  // ── New York City neighborhoods ──────────────────────────────────────────
  "Williamsburg, Brooklyn", "Bushwick, Brooklyn", "Bed-Stuy, Brooklyn", "Crown Heights, Brooklyn",
  "Park Slope, Brooklyn", "Greenpoint, Brooklyn", "Flatbush, Brooklyn", "Bay Ridge, Brooklyn",
  "Borough Park, Brooklyn", "Bensonhurst, Brooklyn", "Sunset Park, Brooklyn", "Cobble Hill, Brooklyn",
  "Red Hook, Brooklyn", "Canarsie, Brooklyn", "East Flatbush, Brooklyn", "Brownsville, Brooklyn",
  "Astoria, Queens", "Flushing, Queens", "Jamaica, Queens", "Jackson Heights, Queens",
  "Forest Hills, Queens", "Ridgewood, Queens", "Long Island City, Queens", "Elmhurst, Queens",
  "Corona, Queens", "Woodside, Queens", "Sunnyside, Queens", "Bayside, Queens",
  "Harlem, Manhattan", "East Harlem, Manhattan", "Washington Heights, Manhattan", "Inwood, Manhattan",
  "Upper East Side, Manhattan", "Upper West Side, Manhattan", "Midtown, Manhattan",
  "Hell's Kitchen, Manhattan", "Chelsea, Manhattan", "Greenwich Village, Manhattan",
  "Lower East Side, Manhattan", "Chinatown, Manhattan", "Tribeca, Manhattan", "SoHo, Manhattan",
  "Mott Haven, Bronx", "Fordham, Bronx", "Pelham Bay, Bronx", "Riverdale, Bronx",
  "Tremont, Bronx", "Highbridge, Bronx", "Morris Heights, Bronx", "Co-op City, Bronx",
  // ── Los Angeles area ─────────────────────────────────────────────────────
  "Silver Lake, Los Angeles", "Echo Park, Los Angeles", "Highland Park, Los Angeles",
  "Koreatown, Los Angeles", "Mid-City, Los Angeles", "Boyle Heights, Los Angeles",
  "North Hollywood, Los Angeles", "Van Nuys, Los Angeles", "Reseda, Los Angeles",
  "Chatsworth, Los Angeles", "Canoga Park, Los Angeles", "Westlake, Los Angeles",
  "Inglewood, California", "Compton, California", "Hawthorne, California",
  "Torrance, California", "Carson, California", "Gardena, California",
  "Santa Monica, California", "Culver City, California", "El Monte, California",
  "Pomona, California", "Ontario, California", "Riverside, California",
  "San Bernardino, California", "Anaheim, California", "Santa Ana, California",
  "Irvine, California", "Huntington Beach, California", "Glendale, California",
  "Pasadena, California", "Burbank, California", "Santa Clarita, California",
  // ── San Francisco Bay Area ────────────────────────────────────────────────
  "Mission District, San Francisco", "Castro, San Francisco", "Tenderloin, San Francisco",
  "Richmond, San Francisco", "Sunset, San Francisco", "Noe Valley, San Francisco",
  "Haight-Ashbury, San Francisco", "Bayview, San Francisco", "SoMa, San Francisco",
  "Fremont, California", "Hayward, California", "Berkeley, California",
  "San Leandro, California", "Daly City, California", "Richmond, California",
  "San Jose, California", "San Mateo, California", "Redwood City, California",
  "Sunnyvale, California", "Santa Clara, California", "Mountain View, California",
  // ── Texas ────────────────────────────────────────────────────────────────
  "Midtown, Houston", "Montrose, Houston", "Heights, Houston", "East End, Houston",
  "Third Ward, Houston", "Sunnyside, Houston", "Pasadena, Texas", "Pearland, Texas",
  "Sugar Land, Texas", "Katy, Texas", "The Woodlands, Texas", "Baytown, Texas",
  "Garland, Texas", "Irving, Texas", "Mesquite, Texas", "Carrollton, Texas",
  "Grand Prairie, Texas", "McKinney, Texas", "Frisco, Texas", "Plano, Texas",
  "Round Rock, Texas", "Cedar Park, Texas", "Georgetown, Texas", "Pflugerville, Texas",
  "Lubbock, Texas", "Amarillo, Texas", "Laredo, Texas", "Brownsville, Texas",
  "McAllen, Texas", "Midland, Texas", "Odessa, Texas", "Waco, Texas",
  "Beaumont, Texas", "Killeen, Texas", "Abilene, Texas", "Tyler, Texas",
  // ── Florida ──────────────────────────────────────────────────────────────
  "Little Havana, Miami", "Wynwood, Miami", "Overtown, Miami", "Allapattah, Miami",
  "Coral Gables, Florida", "Doral, Florida", "Kendall, Florida", "Homestead, Florida",
  "Pembroke Pines, Florida", "Miramar, Florida", "Hollywood, Florida", "Pompano Beach, Florida",
  "Boca Raton, Florida", "Delray Beach, Florida", "West Palm Beach, Florida",
  "Cape Coral, Florida", "Fort Myers, Florida", "Naples, Florida", "Sarasota, Florida",
  "Clearwater, Florida", "Brandon, Florida", "Lakeland, Florida", "Gainesville, Florida",
  "Tallahassee, Florida", "Pensacola, Florida", "Ocala, Florida",
  // ── Illinois / Midwest ───────────────────────────────────────────────────
  "Logan Square, Chicago", "Pilsen, Chicago", "Wicker Park, Chicago", "Lakeview, Chicago",
  "Lincoln Park, Chicago", "Hyde Park, Chicago", "Bronzeville, Chicago", "Humboldt Park, Chicago",
  "Rogers Park, Chicago", "Avondale, Chicago", "Bridgeport, Chicago", "Back of the Yards, Chicago",
  "Evanston, Illinois", "Aurora, Illinois", "Joliet, Illinois", "Naperville, Illinois",
  "Rockford, Illinois", "Springfield, Illinois", "Peoria, Illinois",
  "Detroit, Michigan", "Grand Rapids, Michigan", "Warren, Michigan", "Sterling Heights, Michigan",
  "Lansing, Michigan", "Ann Arbor, Michigan", "Dearborn, Michigan", "Flint, Michigan",
  "Milwaukee, Wisconsin", "Madison, Wisconsin", "Green Bay, Wisconsin",
  "Minneapolis, Minnesota", "Saint Paul, Minnesota", "Rochester, Minnesota",
  // ── Ohio / Indiana / Kentucky ────────────────────────────────────────────
  "Short North, Columbus", "German Village, Columbus", "Clintonville, Columbus",
  "Tremont, Cleveland", "Ohio City, Cleveland", "Little Italy, Cleveland",
  "Over-the-Rhine, Cincinnati", "Mount Auburn, Cincinnati", "Northside, Cincinnati",
  "Akron, Ohio", "Dayton, Ohio", "Youngstown, Ohio", "Canton, Ohio",
  "Fort Wayne, Indiana", "Evansville, Indiana", "South Bend, Indiana", "Gary, Indiana",
  "Lexington, Kentucky", "Bowling Green, Kentucky", "Covington, Kentucky",
  // ── Southeast ────────────────────────────────────────────────────────────
  "Old Fourth Ward, Atlanta", "East Atlanta, Atlanta", "West End, Atlanta",
  "Little Five Points, Atlanta", "Decatur, Georgia", "Marietta, Georgia",
  "Savannah, Georgia", "Augusta, Georgia", "Columbus, Georgia", "Macon, Georgia",
  "North Nashville, Tennessee", "East Nashville, Tennessee", "South Nashville, Tennessee",
  "Knoxville, Tennessee", "Chattanooga, Tennessee", "Clarksville, Tennessee",
  "Birmingham, Alabama", "Montgomery, Alabama", "Huntsville, Alabama", "Mobile, Alabama",
  "Jackson, Mississippi", "Gulfport, Mississippi",
  "Charlotte, North Carolina", "Raleigh, North Carolina", "Durham, North Carolina",
  "Greensboro, North Carolina", "Winston-Salem, North Carolina", "Fayetteville, North Carolina",
  "Columbia, South Carolina", "Charleston, South Carolina", "Greenville, South Carolina",
  "Richmond, Virginia", "Norfolk, Virginia", "Chesapeake, Virginia", "Arlington, Virginia",
  "Alexandria, Virginia", "Hampton, Virginia", "Newport News, Virginia",
  "Baltimore, Maryland", "Silver Spring, Maryland", "Frederick, Maryland",
  // ── Northeast ────────────────────────────────────────────────────────────
  "South Philly, Philadelphia", "North Philly, Philadelphia", "West Philly, Philadelphia",
  "Kensington, Philadelphia", "Fishtown, Philadelphia",
  "Allentown, Pennsylvania", "Erie, Pennsylvania", "Reading, Pennsylvania", "Scranton, Pennsylvania",
  "Newark, New Jersey", "Jersey City, New Jersey", "Paterson, New Jersey",
  "Trenton, New Jersey", "Elizabeth, New Jersey", "Camden, New Jersey",
  "Bridgeport, Connecticut", "New Haven, Connecticut", "Hartford, Connecticut",
  "Providence, Rhode Island", "Springfield, Massachusetts", "Worcester, Massachusetts",
  "Lowell, Massachusetts", "Brockton, Massachusetts", "New Bedford, Massachusetts",
  "Buffalo, New York", "Rochester, New York", "Yonkers, New York", "Syracuse, New York",
  "Albany, New York", "New Rochelle, New York", "Mount Vernon, New York",
  // ── Mountain / Pacific Northwest ─────────────────────────────────────────
  "Aurora, Colorado", "Lakewood, Colorado", "Fort Collins, Colorado", "Colorado Springs, Colorado",
  "Pueblo, Colorado", "Boulder, Colorado",
  "Henderson, Nevada", "North Las Vegas, Nevada", "Reno, Nevada", "Sparks, Nevada",
  "Tucson, Arizona", "Mesa, Arizona", "Chandler, Arizona", "Gilbert, Arizona",
  "Glendale, Arizona", "Scottsdale, Arizona", "Tempe, Arizona", "Peoria, Arizona",
  "Salt Lake City, Utah", "West Valley City, Utah", "Provo, Utah", "Ogden, Utah",
  "Bellevue, Washington", "Tacoma, Washington", "Spokane, Washington", "Vancouver, Washington",
  "Kirkland, Washington", "Renton, Washington", "Redmond, Washington",
  "Eugene, Oregon", "Gresham, Oregon", "Hillsboro, Oregon", "Salem, Oregon",
  "Boise, Idaho", "Nampa, Idaho", "Meridian, Idaho",
  // ── New England / Mid-Atlantic smaller cities ─────────────────────────────
  "Manchester, New Hampshire", "Nashua, New Hampshire",
  "Burlington, Vermont", "Portland, Maine",
  "Wilmington, Delaware", "Dover, Delaware",
  // ── South / Southwest ────────────────────────────────────────────────────
  "Baton Rouge, Louisiana", "Shreveport, Louisiana", "Lafayette, Louisiana", "Metairie, Louisiana",
  "Little Rock, Arkansas", "Fort Smith, Arkansas",
  "Tulsa, Oklahoma", "Oklahoma City, Oklahoma", "Norman, Oklahoma", "Broken Arrow, Oklahoma",
  "Albuquerque, New Mexico", "Santa Fe, New Mexico", "Las Cruces, New Mexico",
  "Wichita, Kansas", "Overland Park, Kansas", "Kansas City, Kansas", "Topeka, Kansas",
  "Omaha, Nebraska", "Lincoln, Nebraska",
  "Sioux Falls, South Dakota", "Rapid City, South Dakota",
  "Fargo, North Dakota", "Bismarck, North Dakota",
  "Billings, Montana", "Great Falls, Montana",
  "Casper, Wyoming", "Cheyenne, Wyoming",
  "Columbia, Missouri", "St. Louis, Missouri", "Springfield, Missouri", "Independence, Missouri",
  "Des Moines, Iowa", "Cedar Rapids, Iowa", "Davenport, Iowa",
  // ── United Kingdom — London neighborhoods ─────────────────────────────────
  "Shoreditch, London", "Hackney, London", "Brixton, London", "Peckham, London",
  "Dalston, London", "Bethnal Green, London", "Whitechapel, London", "Bow, London",
  "Stratford, London", "Forest Gate, London", "Ilford, London", "Barking, London",
  "Woolwich, London", "Plumstead, London", "Eltham, London", "Catford, London",
  "Lewisham, London", "Deptford, London", "New Cross, London", "Brockley, London",
  "Penge, London", "Crystal Palace, London", "Norwood, London", "Streatham, London",
  "Tooting, London", "Balham, London", "Clapham, London", "Stockwell, London",
  "Kennington, London", "Elephant & Castle, London", "Bermondsey, London", "Rotherhithe, London",
  "Canada Water, London", "Surrey Quays, London", "Nunhead, London", "Honor Oak, London",
  "Dulwich, London", "Herne Hill, London", "West Norwood, London", "Thornton Heath, London",
  "Mitcham, London", "Morden, London", "Wimbledon, London", "Tooting, London",
  "Wandsworth, London", "Putney, London", "Fulham, London", "Hammersmith, London",
  "Shepherd's Bush, London", "Acton, London", "Ealing, London", "Southall, London",
  "Hayes, London", "Hounslow, London", "Feltham, London", "Twickenham, London",
  "Richmond, London", "Kingston, London", "Surbiton, London", "Sutton, London",
  "Croydon, London", "Thornton Heath, London", "Norbury, London", "Colliers Wood, London",
  "Camden, London", "Islington, London", "Finsbury Park, London", "Holloway, London",
  "Archway, London", "Tufnell Park, London", "Gospel Oak, London", "Kentish Town, London",
  "Highgate, London", "Muswell Hill, London", "Wood Green, London", "Tottenham, London",
  "Edmonton, London", "Enfield, London", "Walthamstow, London", "Leyton, London",
  "Leytonstone, London", "Wanstead, London", "Woodford, London", "Chingford, London",
  "Bromley, London", "Beckenham, London", "Orpington, London", "Sidcup, London",
  "Bexleyheath, London", "Dartford, London", "Erith, London", "Belvedere, London",
  // ── United Kingdom — England ──────────────────────────────────────────────
  "Birmingham, England", "Manchester, England", "Leeds, England", "Sheffield, England",
  "Bradford, England", "Liverpool, England", "Bristol, England", "Coventry, England",
  "Nottingham, England", "Leicester, England", "Kingston upon Hull, England",
  "Stoke-on-Trent, England", "Wolverhampton, England", "Derby, England",
  "Southampton, England", "Portsmouth, England", "Brighton, England",
  "Plymouth, England", "Exeter, England", "Gloucester, England",
  "Oxford, England", "Cambridge, England", "Norwich, England", "Ipswich, England",
  "Luton, England", "Watford, England", "Milton Keynes, England", "Northampton, England",
  "Peterborough, England", "Lincoln, England", "Grimsby, England",
  "Middlesbrough, England", "Sunderland, England", "Newcastle upon Tyne, England",
  "Gateshead, England", "Hartlepool, England", "Stockton-on-Tees, England",
  "Blackpool, England", "Preston, England", "Blackburn, England", "Burnley, England",
  "Bolton, England", "Wigan, England", "Salford, England", "Rochdale, England",
  "Oldham, England", "Stockport, England", "Warrington, England",
  "Huddersfield, England", "Wakefield, England", "Rotherham, England", "Barnsley, England",
  "Doncaster, England", "Chesterfield, England",
  "Swansea, Wales", "Cardiff, Wales", "Newport, Wales",
  "Glasgow, Scotland", "Edinburgh, Scotland", "Aberdeen, Scotland", "Dundee, Scotland",
  "Inverness, Scotland", "Stirling, Scotland", "Perth, Scotland",
  "Belfast, Northern Ireland", "Derry, Northern Ireland",
  // ── Canada ────────────────────────────────────────────────────────────────
  "Scarborough, Toronto", "North York, Toronto", "Etobicoke, Toronto", "East York, Toronto",
  "Downtown Toronto, Ontario", "Mississauga, Ontario", "Brampton, Ontario", "Markham, Ontario",
  "Richmond Hill, Ontario", "Vaughan, Ontario", "Oakville, Ontario", "Burlington, Ontario",
  "Hamilton, Ontario", "Kitchener, Ontario", "Waterloo, Ontario", "Cambridge, Ontario",
  "London, Ontario", "Windsor, Ontario", "Oshawa, Ontario", "Barrie, Ontario",
  "Guelph, Ontario", "St. Catharines, Ontario", "Kingston, Ontario", "Sudbury, Ontario",
  "Thunder Bay, Ontario", "Ottawa, Ontario", "Gatineau, Quebec",
  "Montreal, Quebec", "Laval, Quebec", "Longueuil, Quebec", "Sherbrooke, Quebec",
  "Saguenay, Quebec", "Lévis, Quebec", "Trois-Rivières, Quebec", "Terrebonne, Quebec",
  "Calgary, Alberta", "Edmonton, Alberta", "Red Deer, Alberta", "Lethbridge, Alberta",
  "Medicine Hat, Alberta", "St. Albert, Alberta", "Grande Prairie, Alberta",
  "Vancouver, British Columbia", "Surrey, British Columbia", "Burnaby, British Columbia",
  "Richmond, British Columbia", "Kelowna, British Columbia", "Abbotsford, British Columbia",
  "Coquitlam, British Columbia", "Langley, British Columbia", "Saanich, British Columbia",
  "Winnipeg, Manitoba", "Brandon, Manitoba",
  "Saskatoon, Saskatchewan", "Regina, Saskatchewan",
  "Halifax, Nova Scotia", "Cape Breton, Nova Scotia",
  "Moncton, New Brunswick", "Fredericton, New Brunswick", "Saint John, New Brunswick",
  // ── Australia ─────────────────────────────────────────────────────────────
  "Parramatta, New South Wales", "Liverpool, New South Wales", "Blacktown, New South Wales",
  "Penrith, New South Wales", "Campbelltown, New South Wales", "Bankstown, New South Wales",
  "Auburn, New South Wales", "Fairfield, New South Wales", "Cabramatta, New South Wales",
  "Cronulla, New South Wales", "Hurstville, New South Wales", "Kogarah, New South Wales",
  "Newtown, New South Wales", "Surry Hills, New South Wales", "Redfern, New South Wales",
  "Marrickville, New South Wales", "Leichhardt, New South Wales", "Glebe, New South Wales",
  "Manly, New South Wales", "Chatswood, New South Wales", "Hornsby, New South Wales",
  "Wollongong, New South Wales", "Newcastle, New South Wales", "Maitland, New South Wales",
  "Footscray, Victoria", "Sunshine, Victoria", "St Kilda, Victoria", "Fitzroy, Victoria",
  "Collingwood, Victoria", "Richmond, Victoria", "Brunswick, Victoria", "Northcote, Victoria",
  "Dandenong, Victoria", "Frankston, Victoria", "Ringwood, Victoria", "Knox, Victoria",
  "Geelong, Victoria", "Ballarat, Victoria", "Bendigo, Victoria", "Shepparton, Victoria",
  "Fortitude Valley, Queensland", "Ipswich, Queensland", "Toowoomba, Queensland",
  "Rockhampton, Queensland", "Mackay, Queensland", "Townsville, Queensland",
  "Cairns, Queensland", "Logan, Queensland", "Redland, Queensland", "Moreton Bay, Queensland",
  "Fremantle, Western Australia", "Midland, Western Australia", "Armadale, Western Australia",
  "Rockingham, Western Australia", "Mandurah, Western Australia", "Joondalup, Western Australia",
  "Stirling, Western Australia", "Swan, Western Australia",
  "Salisbury, South Australia", "Onkaparinga, South Australia", "Port Adelaide, South Australia",
  "Gawler, South Australia", "Mount Gambier, South Australia",
  "Hobart, Tasmania", "Launceston, Tasmania",
  "Darwin, Northern Territory", "Palmerston, Northern Territory",
  "Canberra, Australian Capital Territory",
  // ── New Zealand ───────────────────────────────────────────────────────────
  "Auckland, New Zealand", "Manukau, New Zealand", "North Shore, New Zealand",
  "Waitakere, New Zealand", "Wellington, New Zealand", "Christchurch, New Zealand",
  "Hamilton, New Zealand", "Tauranga, New Zealand", "Dunedin, New Zealand",
  "Palmerston North, New Zealand", "Nelson, New Zealand", "Rotorua, New Zealand",
  // ── Ireland ───────────────────────────────────────────────────────────────
  "Dublin 1, Ireland", "Dublin 7, Ireland", "Dublin 8, Ireland", "Dublin 12, Ireland",
  "Cork, Ireland", "Limerick, Ireland", "Galway, Ireland", "Waterford, Ireland",
  "Drogheda, Ireland", "Dundalk, Ireland",
];

export default CITIES;
